minimum_pre_commit_version: "4.0.0"

default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args:
          - --maxkb=1024

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff
        args:
          - --select=E4,E7,E9,F
          - --output-format=concise
        types_or:
          - python
          - pyi
      - id: ruff-format
        types_or:
          - python
          - pyi

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
          - pre-push
