FEATURES_DIR = "data/features/"
RESULTS_DIR = "results/"

# Training constants
FINAL_ESTIMATOR_BUFFER = 20
FINAL_ESTIMATOR_MULTIPLIER = 1.1
MIN_FINAL_ESTIMATORS = 50
PSEUDO_VAL_MIN_SIZE = 100
PSEUDO_VAL_FRACTION = 0.01  # 1%

# Validation / testing constants
TRADING_DAYS_PER_MONTH = 21
BARS_PER_TRADING_DAY = 390  # 1-minute bars in 6.5 hour trading day
DEFAULT_WFV_FOLD_SIZE = TRADING_DAYS_PER_MONTH * BARS_PER_TRADING_DAY
DEFAULT_WFV_FOLDS = 6
PSEUDO_VAL_MIN_SIZE = 100
PSEUDO_VAL_FRACTION = 0.05  # 5% of training data
